version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1286267066
      MYSQL_DATABASE: cloud-project
      MYSQL_USER: root
      MYSQL_PASSWORD: 1286267066
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    ports:
      - "3020:3020"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: cloud-project
      USER: root
      PASSWORD: 1286267066
      DATABASE_PORT: 3307
      JWT_SECRET_KEY: tawfik
      PORT: 3020
      JWT_SECRET: tawfik_tarek_tawfik

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
